name: Build and Publish on NPM
on:
    push:
        branches:
            - master
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 'v18.13.0'
                  registry-url: 'https://registry.npmjs.org'
            - name: Build and publish
              env:
                  NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
              run: |
                  npm install
                  npm run build
                  npm publish --access public
